DROP TABLE IF EXISTS currency;
CREATE TABLE IF NOT EXISTS currency(
    id IDENTITY NOT NULL PRIMARY KEY,
    code VARCHAR(5) NOT NULL UNIQUE,
    chinese_name VARCHAR(10) NOT NULL UNIQUE,
    symbol VARCHAR(10) NOT NULL UNIQUE,
    rate DECIMAL(15, 5) NOT NULL,
    description VARCHAR(100),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP
);